apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: message
spec:
  template:
    spec:
      containers:
        - name: message
          ports:
            - containerPort: 8080
              $patch: delete
            - name: message-port
              containerPort: 9090
          args:
            - --readinessStart=$(REDINESS_START)
            - --logtostderr
            - --v=$(LOG_LEVEL)
          readinessProbe:
            httpGet:
              port: message-port
          livenessProbe:
            httpGet:
              port: message-port


