apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: bugbuilder/message:latest
          imagePullPolicy: IfNotPresent
          args:
            - --readinessStart=10
            - --logtostderr
            - --v=1
          ports:
            - name: message-port
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: message-configmap
          resources:
            requests:
              memory: 10Mi
              cpu: 20m
            limits:
              memory: 30Mi
              cpu: 100m
          volumeMounts:
            - name: message-config
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /ready
              port: message-port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: message-port
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: message-config
          configMap:
            name: message-configmap
